# Generated by Django 3.0.1 on 2020-02-16 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ['-score']},
        ),
    ]
