# Generated by Django 3.0.3 on 2020-02-19 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0002_company'),
        ('movies', '0002_auto_20200216_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviegenre',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_genres', to='metadata.Genre', verbose_name='Genre'),
        ),
    ]
