# Generated by Django 3.0.3 on 2020-02-19 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0002_company'),
        ('movies', '0003_auto_20200219_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieactor',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actors', to='movies.Movie', verbose_name='Movie'),
        ),
        migrations.AlterField(
            model_name='moviecompany',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='movies.Movie', verbose_name='Movie'),
        ),
        migrations.AlterField(
            model_name='moviecountry',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='movies.Movie', verbose_name='Movie'),
        ),
        migrations.AlterField(
            model_name='moviedirector',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directors', to='movies.Movie', verbose_name='Movie'),
        ),
        migrations.AlterField(
            model_name='moviegenre',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metadata.Genre', verbose_name='Genre'),
        ),
        migrations.AlterField(
            model_name='moviegenre',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genres', to='movies.Movie', verbose_name='Movie'),
        ),
        migrations.AlterField(
            model_name='movielanguage',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='movies.Movie', verbose_name='Movie'),
        ),
    ]
