# Generated by Django 3.0.3 on 2020-02-19 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0002_company'),
        ('movies', '0004_auto_20200219_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieactor',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actors', to='metadata.Person', verbose_name='Actor'),
        ),
        migrations.AlterField(
            model_name='moviecompany',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='metadata.Company', verbose_name='Production company'),
        ),
        migrations.AlterField(
            model_name='moviecountry',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='metadata.Country', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='moviedirector',
            name='director',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directors', to='metadata.Person', verbose_name='Director'),
        ),
        migrations.AlterField(
            model_name='moviegenre',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genres', to='metadata.Genre', verbose_name='Genre'),
        ),
        migrations.AlterField(
            model_name='movielanguage',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='metadata.Language', verbose_name='Language'),
        ),
    ]
